language: node_js
node_js:
  - 14

script:
  - npm run build
  - cat .gitignore | grep -v 'css/style.css' > .gitignore-new
  - mv .gitignore-new .gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
